# Setup
title:        Post
tagline:      A simple package manager for linux systems.
baseurl:      "http://leximch.github.io/post"
paginate:     1

# About/contact
author:
  name:       Alexandra Chace
  url:        http://leximch.wordpress.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet