# Setup
title:        Post
tagline:      A simple package manager for linux systems.
baseurl:      "http://marilync.co/post/"
paginate:     1
github:       "http://github.com/marilyncco/post/"

# About/contact
author:
  name:       Alexandra Chace
  url:        http://leximch.wordpress.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
