# Setup
title:        Post
tagline:      A simple package manager for linux systems.
baseurl:      "https://alychace.com/post/"
paginate:     1
github:       "http://github.com/leximch/post/"

# About/contact
author:
  name:       Aly Chace
  url:        https://alychace.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
